name: deploy-container

# run this when we make a change to container
on:
  push:
    branches:
      - master
    paths: 
      - 'packages/container/**'

# set exec environment, e.g. for npm install
defaults:
  run:
    working-directory: packages/container

# one job to build and deploy
jobs:
  build:
    # Github VM
    runs-on: ubuntu-latest
    steps:
      # checkout code
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      # deploy to S3, using AWS CLI
      # - uses: shinyinc/action-aws-cli@v1.2
      - run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
